[versions]
ktx = "1.12.0"
androidGradlePlugin = "8.1.0"
jetbrainsKotlinAndroid = "1.9.0"

[libraries]
androidx-ktx = {group= "androidx.core", name = "core-ktx", version.ref = "ktx" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrainsKotlinAndroid" }
